### ISSUE TITLE
<HttpError 400 

### ISSUE THREAD

**Issue by diogo098** [WastefulNick/YouTube-Commenter#1]
<HttpError 400 when requesting https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&alt=json returned "Comments cannot be empty.">

**Comment by WastefulNick** [comment]
Have you filled in all the text files in the "data" folder? If you have, make sure there's no lines in the files that are purely newlines.

**Comment by diogo098** [comment]
I figure it out the issue, i just have 1 line of comments, probably was not enoth, its working amazing with 2 lines, in comment.txt
Thank you so much for everything you are amazing ✌

**Comment by WastefulNick** [comment]
Glad it worked!
