### ISSUE TITLE
Reply ?

### ISSUE THREAD

**Issue by pavel191919191** [WastefulNick/YouTube-Commenter#2]
Hey mate I appreciate your nice job, but the thing is that reply is missing, the option to REPLY to the most top comment will be even massively better, could you do another bot and this time reply ?
thanks!

**Comment by WastefulNick** [comment]
Hey, thanks for the idea. I'll see if I'll have time to add it before the end of the week.

**Comment by pavel191919191** [comment]
I almost forget, it is also important to show in the UI of CMD how many comments it did and also save the comments videos in some text file, I can try to do it but Im more vb.net then py :)
