### ISSUE TITLE
24 comments and finish

### ISSUE THREAD

**Issue by pavel191919191** [WastefulNick/YouTube-Commenter#3]
The API is really bad, it block commenting after 20 or 24 times.
I set 60 sec time then also 300sec its the same.
Google is useles I will try to search something else but thx for effort.

PS: you should add option to add 5 or 10 JSON files and randomize it so we can comment 24/7 on autopilot.
also it is not good to copy the url cmd gives and put it in browser then allow and authorize the user, it should be automatic.

the idea is cool but still needs to run as bot and this task needs to run alone on autopilot else, you can comment and reply faster without using this tool.

**Comment by WastefulNick** [comment]
The API gives you 10 000 quota units per 24 hours. A comment uses 50; so if you haven't used the API at all in the past 24 hours and therefore have max units, you should be able to make 200 (196 with reply mode) comments. Set the timeout to 440sec (~7min) and it should run 24/7 without failing on any comments. 

I do not plan to add the ability to use multiple projects, but it should not be too hard to implement by yourself if you have some programming experience. 

About the copying URL; there is no other way to authenticate the user and there is no way to bypass this; if there was it would be a massive security flaw with OAUTH. However the program does store the info, so you only have to do this once.

**Comment by WastefulNick** [comment]
The API gives you 10 000 quota units per 24 hours. A comment uses 50; so if you haven't used the API at all in the past 24 hours and therefore have max units, you should be able to make 200 (196 with reply mode) comments. Set the timeout to 440sec (~7min) and it should run 24/7 without failing on any comments. 

I do not plan to add the ability to use multiple projects, but it should not be too hard to implement by yourself if you have some programming experience. 

About the copying URL; there is no other way to authenticate the user and there is no way to bypass this; if there was it would be a massive security flaw with OAUTH. However the program does store the info, so you only have to do this once.
